# Generated by Django 5.2.9 on 2026-01-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datchik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('A', models.FloatField(blank=True, null=True)),
                ('B', models.FloatField(blank=True, null=True)),
                ('C', models.FloatField(blank=True, null=True)),
                ('D', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatchikType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('per_day', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatchikFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_1', models.FloatField(blank=True, null=True)),
                ('criterion_2', models.FloatField(blank=True, null=True)),
                ('bosim_MPa', models.CharField(blank=True, max_length=255, null=True)),
                ('bosim_m', models.CharField(blank=True, max_length=255, null=True)),
                ('suv_sathi', models.CharField(blank=True, max_length=255, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=255, null=True)),
                ('suv_sarfi', models.CharField(blank=True, max_length=255, null=True)),
                ('loyqa', models.CharField(blank=True, max_length=255, null=True)),
                ('deformatsiya_x', models.CharField(blank=True, max_length=255, null=True)),
                ('deformatsiya_y', models.CharField(blank=True, max_length=255, null=True)),
                ('deformatsiya_z', models.CharField(blank=True, max_length=255, null=True)),
                ('temperatura_x', models.CharField(blank=True, max_length=255, null=True)),
                ('temperatura_y', models.CharField(blank=True, max_length=255, null=True)),
                ('temperatura_z', models.CharField(blank=True, max_length=255, null=True)),
                ('vektor_ogish_korsatgichi', models.CharField(blank=True, max_length=255, null=True)),
                ('sina', models.CharField(blank=True, max_length=255, null=True)),
                ('sinb', models.CharField(blank=True, max_length=255, null=True)),
                ('datchik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='app.datchik')),
            ],
        ),
        migrations.CreateModel(
            name='DatchikState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_log_at', models.DateTimeField(blank=True, null=True)),
                ('datchik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='app.datchik')),
            ],
        ),
        migrations.AddField(
            model_name='datchik',
            name='datchik_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datchiklar', to='app.datchiktype'),
        ),
        migrations.AddField(
            model_name='datchik',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_datchiks', to='app.direction'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_locations', to='app.direction')),
            ],
        ),
        migrations.AddField(
            model_name='datchik',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_datchiks', to='app.location'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_sections', to='app.direction')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_sections', to='app.location')),
            ],
        ),
        migrations.AddField(
            model_name='datchik',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_datchiks', to='app.section'),
        ),
        migrations.CreateModel(
            name='DataloggerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=10)),
                ('value_type', models.CharField(choices=[('bosim_MPa', 'Bosim_MPa'), ('bosim_m', 'Bosim m'), ('bosim_sm', 'Bosim sm'), ('bosim_mm', 'Bosim mm'), ('deformatsiya_x', 'Deformatsiya X'), ('deformatsiya_y', 'Deformatsiya Y'), ('deformatsiya_z', 'Deformatsiya Z'), ('sina', 'Sin(A)'), ('sinb', 'Sin(B)'), ('vektor_ogish_korsatgichi', "Vektor Og'ish"), ('temperatura', 'Temperatura'), ('temperatura_x', 'Temperatura X'), ('temperatura_y', 'Temperatura Y'), ('temperatura_z', 'Temperatura Z'), ('suv_sathi', 'Suv sathi'), ('suv_sarfi', 'Suv sarfi'), ('loyqa', 'Loyqa')], max_length=50)),
                ('datchik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='app.datchik')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('node_id', 'channel'), name='uniq_node_channel')],
            },
        ),
        migrations.CreateModel(
            name='DatchikLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(db_index=True)),
                ('bosim_MPa', models.FloatField(blank=True, null=True)),
                ('bosim_m', models.FloatField(blank=True, null=True)),
                ('bosim_sm', models.FloatField(blank=True, null=True)),
                ('bosim_mm', models.FloatField(blank=True, null=True)),
                ('deformatsiya_x', models.FloatField(blank=True, null=True)),
                ('deformatsiya_y', models.FloatField(blank=True, null=True)),
                ('deformatsiya_z', models.FloatField(blank=True, null=True)),
                ('temperatura_x', models.FloatField(blank=True, null=True)),
                ('temperatura_y', models.FloatField(blank=True, null=True)),
                ('temperatura_z', models.FloatField(blank=True, null=True)),
                ('vektor_ogish_korsatgichi', models.FloatField(blank=True, null=True)),
                ('sina', models.FloatField(blank=True, null=True)),
                ('sinb', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('suv_sathi', models.FloatField(blank=True, null=True)),
                ('suv_sarfi', models.FloatField(blank=True, null=True)),
                ('loyqa', models.FloatField(blank=True, null=True)),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.datchikformula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('formula', 'sana'), name='uniq_log_formula_sana')],
            },
        ),
        migrations.CreateModel(
            name='RawReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('value_type', models.CharField(choices=[('bosim_MPa', 'Bosim_MPa'), ('bosim_m', 'Bosim m'), ('bosim_sm', 'Bosim sm'), ('bosim_mm', 'Bosim mm'), ('deformatsiya_x', 'Deformatsiya X'), ('deformatsiya_y', 'Deformatsiya Y'), ('deformatsiya_z', 'Deformatsiya Z'), ('sina', 'Sin(A)'), ('sinb', 'Sin(B)'), ('vektor_ogish_korsatgichi', "Vektor Og'ish"), ('temperatura', 'Temperatura'), ('temperatura_x', 'Temperatura X'), ('temperatura_y', 'Temperatura Y'), ('temperatura_z', 'Temperatura Z'), ('loyqa', 'Loyqa'), ('suv_sathi', 'Suv sathi'), ('suv_sarfi', 'Suv sarfi')], db_index=True, max_length=50)),
                ('raw_value', models.FloatField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datchik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_readings', to='app.datchik')),
            ],
            options={
                'indexes': [models.Index(fields=['datchik', 'ts'], name='app_rawread_datchik_5c3e44_idx'), models.Index(fields=['value_type', 'ts'], name='app_rawread_value_t_0523a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('datchik', 'ts', 'value_type'), name='uniq_raw_datchik_ts_type')],
            },
        ),
    ]
