# Generated by Django 5.2.9 on 2025-12-23 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datchik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=255)),
                ('criterion_1', models.FloatField(blank=True, null=True)),
                ('criterion_2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatchikLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('humidity', models.CharField(blank=True, max_length=50, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('water_high_pizometr', models.FloatField(blank=True, null=True)),
                ('water_high_bef', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('water_consumption', models.FloatField(blank=True, null=True)),
                ('blur_level', models.FloatField(blank=True, null=True)),
                ('deviation_indicator', models.FloatField(blank=True, null=True)),
                ('sin_A', models.FloatField(blank=True, null=True)),
                ('sin_B', models.FloatField(blank=True, null=True)),
                ('shift_X', models.FloatField(blank=True, null=True)),
                ('shift_Y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datchik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.datchik')),
            ],
        ),
        migrations.AddField(
            model_name='datchik',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_datchiks', to='app.direction'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_locations', to='app.direction')),
            ],
        ),
        migrations.AddField(
            model_name='datchik',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_datchiks', to='app.location'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='sections/')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_sections', to='app.direction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_sections', to='app.location')),
            ],
        ),
        migrations.AddField(
            model_name='datchik',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_datchiks', to='app.section'),
        ),
    ]
