# Generated by Django 5.2.9 on 2025-12-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datchik',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_datchiks', to='app.direction'),
        ),
        migrations.AlterField(
            model_name='datchik',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_datchiks', to='app.section'),
        ),
        migrations.AlterField(
            model_name='datchik',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
