# Generated by Django 5.2.9 on 2025-12-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_datchik_direction_alter_datchik_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datchik',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_datchiks', to='app.direction'),
        ),
        migrations.AlterField(
            model_name='datchik',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datchik',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_datchiks', to='app.location'),
        ),
        migrations.AlterField(
            model_name='datchiklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_locations', to='app.direction'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DatchikFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=255)),
                ('A', models.FloatField(blank=True, null=True)),
                ('B', models.FloatField(blank=True, null=True)),
                ('C', models.FloatField(blank=True, null=True)),
                ('D', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('datchik', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='app.datchik')),
            ],
        ),
    ]
